### ISSUE TITLE
[Bug]从QQ分享到MarkLite时,MarkLite闪退

### ISSUE THREAD

**Issue by Phoenix-Ann** [zhubch/MarkLite#1]
[环境]
IPhone6plus
版本：9.3.2
MarkLIte版本:V1.2&&V1.3

[前置条件]
MarkLite未开启
从手机QQ接收*.md

[步骤]
1.登录QQ，进入“个人中心”——“我的文件”
2.选择一个*.md文件，点击“查看”
3.点击“其他应用打开”
4.选择“拷贝至MarkLite”

[结果]
MarkLite启动页加载过程中闪退

[期望]
可拷贝至MarkLite成功

PS:若MarkLite已提前开启状态下不会出现该问题。

**Comment by zhubinchen** [comment]
嗯，谢谢这么认真的反馈，已经修复了

**Comment by Phoenix-Ann** [comment]
因为很喜欢你开发的应用。！
