### ISSUE TITLE
bug && new requirement

### ISSUE THREAD

**Issue by qindy** [zhubch/MarkLite#10]
1.当点击iCloud时，程序在guard let subPaths = try? fileManager.contentsOfDirectory这行崩溃。
2.希望能添加一个功能：能自动识别在文件共享直接进去的文件。
3.希望能记录上次浏览的位置，并在下次打开时定位到那个位置。

**Comment by zhubinchen** [comment]
1. 已经修复了
2. 苹果的限制，不允许访问所有的iCloud的文件
3. 这个需求实现起来可能有点复杂😂，后续再说
