### ISSUE TITLE
如何和windows同步

### ISSUE THREAD

**Issue by lyallchan** [zhubch/MarkLite#11]
win10上装了icloud for windows，在marklite的icloud上新建了一个文件，结果在ios的icloud driver可以看到新建了一个marklite文件夹，里面有刚才新建的文件，但是在win10上看不到。

**Comment by zhubinchen** [comment]
据我所知，iCloud同步不是即时的，你可以手动备份一下试试
iOS 11系统的步骤：[设置]-[Apple ID]-[iCloud]-[iCloud云备份]-[立即备份]
 ![示意图](https://i.loli.net/2017/09/25/59c896221bff2.jpg)
